sudo: required
services:
  - docker

before_install:
  - docker build -t eglove/ethang-frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true eglove/ethang-frontend yarn test

after_success:
  - docker build -t eglove/ethang-frontend .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push eglove/ethang-frontend

language: generic
