version: '3'
services:
  ethang-frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "7000:7000"
    volumes:
    - .:/app
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    command: ["yarn", "test:watch"]
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
