name: "EthanG Dev CI"

on:
  push:
    branches: [ develop ]
  schedule:
    - cron: '43 21 * * 3'

jobs:
  browsersUpdate:
    name: Browsers Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Browsers List
        run: npx browserslist@latest --update-db
      - name: Commit Changes
        continue-on-error: true
        run: |
          git config --global user.name 'eglove'
          git config --global user.email 'eglove@users.noreply.github.com'
          git commit -am 'Browsers Update'
          git push

  test:
    needs: [ browsersUpdate ]
    name: Node Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: yarn test

  analyze:
    needs: [ browsersUpdate ]
    name: Security Analysis
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  sonar:
    needs: [ browsersUpdate ]
    name: Sonar Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dockerPush:
    needs: [ test, analyze, sonar ]
    name: Push Image To Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Meta
        id: meta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          images: |
            eglove/ethang-frontend
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{pattern}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  mainMerge:
    name: Merge to Main
    needs: [ dockerPush ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to Main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          target_branch: main
          github_token: ${{ github.token }}
